### ISSUE TITLE
remove 167.99.242.112 from DOHipv4

### ISSUE THREAD

**Issue by darkounet** [jpgpi250/piholemanual#10]
This IP is use by a *.gouv.fr domain

https://openacademie.beta.gouv.fr/

Please remove from the DOHipv4 list.

**Comment by jpgpi250** [comment]
done, it was auto-removed last night, however, the repository runs one day behind my test environment (to alllow me to catch /remove really bad entries). Forced a run just now and verified the entry was no longer in the repository.

**Comment by jpgpi250** [comment]
closed after 21 days without response
