### ISSUE TITLE
https://raw.githubusercontent.com/oneoffdallas/dohservers/master/list.txt  - Out of sync

### ISSUE THREAD

**Issue by Bingo600** [jpgpi250/piholemanual#11]
First off - THANK YOU for your great effort, excellent pdf documents , and the "Best" DoH blocklist "known to mankind" :-)

On 
https://github.com/oneoffdallas/dohservers

I noticed the below  list.txt is 4 month old
https://raw.githubusercontent.com/oneoffdallas/dohservers/master/list.txt

Whereas the iplist.txt is 3 month old.
https://raw.githubusercontent.com/oneoffdallas/dohservers/master/iplist.txt

Some ip addresses has been committed
https://github.com/oneoffdallas/dohservers/commit/59f4d33fd16d64f31214235c6614dd6d011a9c20

As i use pfSense (great pdf guide) i'm using your list , and "dallas" iplist.txt , and noticed that a lot of 45.90.30.xx entries was missing from your list.
Actually seems like he added a full 45.90.30.x/24 as single ip entries.

Maybe you could just switch to the iplist instead.

Thanx from Denmark
/Bingo

**Comment by jpgpi250** [comment]
How the script works:
- extract dns names from the lists
- get the ip address and cname info using dig
- if the ip address is valid, add the ip address to the list

you noticed some (not all) missing 45.x.x.x. This problem has been looked at and explained [here](https://github.com/jpgpi250/piholemanual/issues/7)

I want to keep the list reliable (no false positives), thus only adding IP addresses that are the result of a succesful dig, however, as explained in issue 7, the list may be incorrect in different regions. The only solution is to generate the list locally (on one of your machines)

Some dig results:
- dig -x 45.90.57.121 result: vds-841128.hosted-by-itldc.com -> this domain is not in any list, thus the ip will never be in my lists.
- dig -x 45.90.28.1 result: dns1.nextdns.io -> this domain appears in 10 lists
dig dns1.nextdns.io result: 185.18.148.91 (and CNAME dns1.steering.nextdns.io) -> this IP address is in the list, the domain name resolves to this IP in MY REGION, it may be different for you. The CNAME is in the cnameinfo table ([DOH database](https://github.com/jpgpi250/piholemanual/blob/master/DOH.db)). This IP is NOT in the oneoffdallas ip list. Some internet articles I found (search for doh nextdns.io) indicate DoH requests to nextdns.io are redirected to steering.nextdns.io (the actual DoH server).

It may (or may not - false positives) be a good idea to use the IP lists from oneoffdallas, however I can NOT verify these are DoH servers and will NOT be adding these addresses to the list.

Browsing the web will provide other lists ([example](https://codeberg.org/unixsheikh/dohblockbuster)). The problem for my script remains the same: I cannot confirm/deny these are actually DoH servers. That is why I don't use these lists.

Hope this helps...

**Comment by Bingo600** [comment]
I get the reason , and totally agree. Better to leave one off , that get false positives.
I'll close this one 

Thank you
