### ISSUE TITLE
Block NextDNS DoH

### ISSUE THREAD

**Issue by Sn0whax** [jpgpi250/piholemanual#13]
DOHipv4.txt should have the following added (From what i can see)

188.172.221.9
103.127.29.198
217.146.10.59
45.90.28.0
45.90.30.0

**Comment by jpgpi250** [comment]
my results
ipv4:
- public.dns.iij.jp -> 103.2.57.5 and 103.2.57.6
- chromium.dns.nextdns.io, dns1.nextdns.io, dns.nextdns.io, ... 
firefox.dns.nextdns.io, steering.nextdns.io, trr.dns.nextdns.io -> 185.18.148.91

ipv6:
- public.dns.iij.jp -> 2001:300::5 and 2001:300::6
- chromium.dns.nextdns.io, dns1.nextdns.io, dns.nextdns.io, ... 
firefox.dns.nextdns.io, steering.nextdns.io, trr.dns.nextdns.io -> 2a04:b80:1:30::2

as mentioned several times in previous issues, regional difference? To ensure you have a regional correct list, you need to build the ip lists from the domain entries in the [database](https://github.com/jpgpi250/piholemanual/blob/master/DOH.db), as explained in previous issues and the [manual](https://github.com/jpgpi250/piholemanual/blob/master/doc/Block%20DOH%20with%20pfsense.pdf).

please confirm this is a regional issue...

**Comment by jpgpi250** [comment]
closed after 21 days
