### ISSUE TITLE
Block Disconnect DOH server

### ISSUE THREAD

**Issue by ajkblue** [jpgpi250/piholemanual#14]
The various disconnect.me apps use their own DOH provider which is not included on this blocklist, such as the [Disconnect Privacy DNS App](https://apps.apple.com/app/apple-store/id1571342218) and [Disconnect Privacy Pro](https://itunes.apple.com/us/app/privacy-pro-protection-for/id1051960818) on the App Store.

My Pi-Hole shows the lookup for their server as being "doh.disconnect.app":
<img width="1059" alt="Screen Shot 2022-05-30 at 4 06 21 PM" src="https://user-images.githubusercontent.com/9651939/171063580-e0ac15e6-5903-4bf6-a999-083decbfd382.png">

An nslookup gives me these ip's for that domain:
```
% nslookup doh.disconnect.app
Server:		10.1.1.1
Address:	10.1.1.1#53

Non-authoritative answer:
Name:	doh.disconnect.app
Address: 104.21.65.52
Name:	doh.disconnect.app
Address: 172.67.140.171
```

**Comment by jpgpi250** [comment]
As you can see in my [manual](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf), My script processes (daily) existing lists and return usable lists ( ip, rpz ) and the database (to allow users to get regioanal IP addresses) on github. If you can point me to a list / web page /source code that contains these domains, I'll look at it, and possibly add this to the list of lists to process.

**Comment by jpgpi250** [comment]
after creating an [issue](https://github.com/oneoffdallas/dohservers/issues/27), the domain has been added, domain now in RPZfile , IP in IPv4 list
