### ISSUE TITLE
Website in PiHole Blocklist

### ISSUE THREAD

**Issue by DaisukeVN** [jpgpi250/piholemanual#21]
Hey jpgpi250,

can I ask you why the page "daisukivn.asuscomm.com" is inside your blocklist?
Is there a reason? Did you recognized attacks from this domain?

You can keep the Domain in the blacklist if you want. 
I just need to know if there are problems with my Server

Best Regards
![grafik](https://user-images.githubusercontent.com/4640928/218128392-980608f4-fa5a-4a02-8151-b6a133677241.png)

**Comment by jpgpi250** [comment]
There is a DoH server on this domain, according to https://raw.githubusercontent.com/jbaggs/doh-intel/master/doh.intel.

The rpz file contains a collection of domains, hosting a DoH server, consolidated from various lists.
