### ISSUE TITLE
Typos in Block DNS over HTTPS (DoH), using pfsense PDF

### ISSUE THREAD

**Issue by teamits** [jpgpi250/piholemanual#22]
https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf

Noticed a few typos...
1) prevents canary domains from working:
local-zone: " use-application-dns.net." always_nxdomain
local-zone: " mask.icloud.com." always_nxdomain
local-zone: " mask-h2.icloud.com." always_nxdomain

should not have a leading space...with it the domain does resolve, in my testing:
local-zone: "use-application-dns.net." always_nxdomain
local-zone: "mask.icloud.com." always_nxdomain
local-zone: "mask-h2.icloud.com." always_nxdomain

2) responibility > responsibility, p.6
"IP addresses for doh1.b-cdn.net needs to be included (user responibility) in the aliases"

Thanks for the write-up and list!!

**Comment by jpgpi250** [comment]
thanks for reporting this, updated the doc, pushed to github.
