### ISSUE TITLE
python-visualization.github.io blocked 

### ISSUE THREAD

**Issue by adripa45** [jpgpi250/piholemanual#26]
Hi,
An organization we're managing needs access to the website python-visualization.github.io which IP addresses are contained in the DOHipv4.txt file.
_python-visualization.github.io has address 185.199.108.153
python-visualization.github.io has address 185.199.109.153
python-visualization.github.io has address 185.199.110.153
python-visualization.github.io has address 185.199.111.153_

Is it possible to remove these IP's?

**Comment by jpgpi250** [comment]
185.199.108.153 resolves to gendos.net 
185.199.109.153 resolves to gendos.net 
185.199.110.153 resolves to gendos.net 
185.199.111.153 resolves to gendos.net 

gendos.net was listed as a DoH server in list 15, https://raw.githubusercontent.com/jbaggs/doh-intel/master/doh.intel, last seen on 2023-01-17 01:09:01 GMT

I don't add domains to lists, I only consolidate various list, that contain DoH domains. you can find the lists I consolidate in the manual, [here](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf)

As explained in the manual, it is the users responsibility to create exceptions, also explained in the manual.

For the above IP's you may want / need to create exceptions
https://api.bgpview.io/ip/185.199.108.153
https://api.bgpview.io/ip/185.199.109.153
https://api.bgpview.io/ip/185.199.110.153
https://api.bgpview.io/ip/185.199.111.153
The result of these inquiry shows that these IP's are managed by "FASTLY", ASN 54113 

If you don't want to create specific IP exceptions, you can create an exception for the network range FASTLY specifies (185.199.108.0/22) , refer to the above queries to bgpview.io.

It is up to you do decide whether or not you want to use the DoH blocklist, it is provided as is (consolidated) with a clear explanation on how to create exceptions.

**Comment by jpgpi250** [comment]
closed after 21 days without response
