### ISSUE TITLE
Removal Request #2

### ISSUE THREAD

**Issue by ghost** [jpgpi250/piholemanual#28]
Hello,

You have falsely listed 144.172.67.5 in your list, this IP is controlled by my company https://github.com/Simulhost and we require you to immediately remove the aforementioned IP.

Kindly respond to this within 72 hours and comply with out request, otherwise we will request GitHub to take your repository down with immediate effect.

**Comment by jpgpi250** [comment]
144.172.67.5 resolves to dns.simulhost.com

dns.simulhost.com was listed as a DoH server in:
- list 7, https://raw.githubusercontent.com/wiki/curl/curl/DNS-over-HTTPS.md, last seen on 2023-01-19 01:09:01 GMT
- list 15, https://raw.githubusercontent.com/jbaggs/doh-intel/master/doh.intel, last seen on 2023-04-06 00:09:01 GMT

I don't add domains/IPs to lists, neither do I perform any scanning. I only consolidate various list, that contain DoH domains. you can find the lists I consolidate in the manual, [here](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf)

As explained in the manual, it is the users responsibility to create exceptions, also explained in the manual.

For the above IP's you may want / need to create an exception
https://api.bgpview.io/ip/144.172.67.5
The result of these inquiry shows that these IP's are managed by "GALAXYGATE", ASN 397031

If you don't want to create specific IP exceptions, you can create an exception for the network range GALAXYGATE specifies (144.172.67.0/24) , refer to the above queries to bgpview.io.

It is up to you do decide whether or not you want to use the DoH blocklist, it is provided as is (consolidated) with a clear explanation on how to create exceptions.

The IP address is obtained using a dig request (dig A +short dns.simulhost.com). I can't imagine this is illegal...
