### ISSUE TITLE
Rumble Video and Images are being blocked 

### ISSUE THREAD

**Issue by DennisFury** [jpgpi250/piholemanual#31]
151.139.128.10 is a CDN for Rumble video and images.

I see it was added earlier this year to DOHipv4.txt, can you remove this?

Otherwise, I have to mirror your list and script to keep this IP removed.

Thanks

**Comment by jpgpi250** [comment]
151.139.128.10 dns-secondary.cloudnx.cloud, listed as DOH server in lists 7, 11, 15, 20, 21, 23
151.139.128.10 q3i6k7j3.stackpathcdn.com, listed as DOH server in lists 7, 15

7: https://raw.githubusercontent.com/wiki/curl/curl/DNS-over-HTTPS.md
11: https://raw.githubusercontent.com/dibdot/DoH-IP-blocklists/master/doh-ipv4.txt
15: https://raw.githubusercontent.com/jbaggs/doh-intel/master/doh.intel
20: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/doh.txt
21: https://raw.githubusercontent.com/beamrod/doh_hostlist/main/host_list.txt
23: https://raw.githubusercontent.com/jsimonetti/public_doh_servers/main/doh_server_domains.list

read the [manual](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf), apply exceptions where needed.

https://api.bgpview.io/ip/151.139.128.10 indicates you'll need a CIDR (network) exception -> 151.139.128.0/24

**Comment by DennisFury** [comment]
TBH, we run opposition too, and it's just childish at this point.  Thanks though.

**Comment by jpgpi250** [comment]
closed after 21 days without response
