### ISSUE TITLE
Cloudflare LB IP as DoH

### ISSUE THREAD

**Issue by Shadesh** [jpgpi250/piholemanual#32]
Hi,

it could be that this IPV4 and IPv6 address shouldn't be in your DoH list.
For me it looks like a normal Cloudflare LB IP pair because the domain
"vroptiker.de" uses this IPs for HTTP/HTTPS.

vroptiker.de has address 172.67.169.38
vroptiker.de has address 104.21.95.14
vroptiker.de has IPv6 address 2606:4700:3031::6815:5f0e
vroptiker.de has IPv6 address 2606:4700:3034::ac43:a926

For now im implementing a exception for this IPs and domain on my firewall.

Best greetings

**Comment by jpgpi250** [comment]
172.67.169.38 -> ftgfw.tk
104.21.95.14 -> ftgfw.tk
2606:4700:3031::6815:5f0e -> ftgfw.tk
2606:4700:3034::ac43:a926 -> ftgfw.tk

ftgfw.tk -> list 15: https://raw.githubusercontent.com/jbaggs/doh-intel/master/doh.intel

required exceptions:
https://api.bgpview.io/ip/172.67.169.38 -> 172.67.160.0/20
https://api.bgpview.io/ip/104.21.95.14 -> 104.21.80.0/20
https://api.bgpview.io/ip/2606:4700:3031::6815:5f0e -> 2606:4700:3031::/48
https://api.bgpview.io/ip/2606:4700:3034::ac43:a926 -> 2606:4700:3034::/48

It's recommended to implement response policy zones ([RPZ](https://jpgpi250.github.io/piholemanual/doc/Unbound%20response%20policy%20zones.pdf)), when defining exceptions.

**Comment by jpgpi250** [comment]
closed after 21 days without response
