### ISSUE TITLE
104.21.87.171

### ISSUE THREAD

**Issue by C0casio45** [jpgpi250/piholemanual#33]
Hey,
104.21.87.171 seems to be a false positive

**Comment by jpgpi250** [comment]
104.21.87.171 -> flumuffel.de
flumuffel.de -> list 15
list 15 = https://github.com/jbaggs/doh-intel

required exceptions (see the [manual](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf
))
https://api.bgpview.io/ip/104.21.87.171 -> 104.21.64.0/19

It's recommended to implement response policy zones ([RPZ](https://jpgpi250.github.io/piholemanual/doc/Unbound%20response%20policy%20zones.pdf)), when defining exceptions.

**Comment by C0casio45** [comment]
Thank you for the response
