### ISSUE TITLE
Invalid IP

### ISSUE THREAD

**Issue by pallebone** [jpgpi250/piholemanual#36]
The DOHipv4 list contains an IP 255.255.255.255 which is causing me some issues.
https://raw.githubusercontent.com/jpgpi250/piholemanual/master/DOHipv4.txt

This is not a valid ip for a dns server in my opinion I use it in a bogon list for example. Can you comment if this is intended?

Kind regards
Pete

**Comment by jpgpi250** [comment]
```
 dig @127.10.10.9 -p 5559 cattery2.eastasia.cloudapp.azure.com

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> @127.10.10.9 -p 5559 cattery2.eastasia.cloudapp.azure.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62533
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;cattery2.eastasia.cloudapp.azure.com. IN A

;; ANSWER SECTION:
cattery2.eastasia.cloudapp.azure.com. 10 IN A   255.255.255.255

;; Query time: 331 msec
;; SERVER: 127.10.10.9#5559(127.10.10.9) (UDP)
;; WHEN: Wed Oct 18 08:38:59 CEST 2023
;; MSG SIZE  rcvd: 81
```
dns query reply above, however shouldn't be in the list, [broadcast address](https://en.wikipedia.org/wiki/Broadcast_address), will be removed removed in next run...

thanx for the info.

**Comment by pallebone** [comment]
Thanks I will check later :)

**Comment by pallebone** [comment]
Thanks all working :)
