### ISSUE TITLE
Letsencrypt validation broken

### ISSUE THREAD

**Issue by markster1700** [jpgpi250/piholemanual#37]
Update on Nov 6, 2023 broke Letsencrypt cert validation with acme.sh

**Comment by jpgpi250** [comment]
need info (ip and/or domain) to provide a meaningful reply.

read the [manual](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf), section device specific exceptions to exclude the undesired ip block.

**Comment by markster1700** [comment]
No worries. I found the issue. Latest version of acme.sh uses DOH from cloudflare for cert validation.
