### ISSUE TITLE
Discord issus: pfsense translates .0 as /24

### ISSUE THREAD

**Issue by MattLParker** [jpgpi250/piholemanual#38]
https://github.com/jpgpi250/piholemanual/blame/2b479f3ede78ea0ba88511c5c46f787d63bbddd4/DOHipv4.txt#L814

**Comment by MattLParker** [comment]
https://www.netify.ai/resources/ips/162.159.128.235 
Entry in list is 162.159.128.0

**Comment by jpgpi250** [comment]
162.159.128.0 -> cnnic-chinatelecom-chinamobile-chinaunicom--bili-d.dahi.icu

cnnic-chinatelecom-chinamobile-chinaunicom--bili-d.dahi.icu in lists:
- 7: https://raw.githubusercontent.com/wiki/curl/curl/DNS-over-HTTPS.md
- 15: https://raw.githubusercontent.com/jbaggs/doh-intel/master/doh.intel
- 23: https://raw.githubusercontent.com/jsimonetti/public_doh_servers/main/doh_server_domains.list

162.159.128.0 is a cloudflared address ,https://www.cloudflare.com/ips-v4, cidr 162.158.0.0/15

if you need an exception, read the section "CIDR (network) Exceptions" in the [manual](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf).

It is recommended to use rpz, when adding exceptions, see [manual](https://jpgpi250.github.io/piholemanual/doc/Unbound%20response%20policy%20zones.pdf),
zone file https://raw.githubusercontent.com/jpgpi250/piholemanual/master/DOH.rpz

**Comment by jpgpi250** [comment]
closed after 21 days without response
