### ISSUE TITLE
Squarespace web servers are listed

### ISSUE THREAD

**Issue by teamits** [jpgpi250/piholemanual#39]
I can see by the Closed issue responses the answer is going to be to create an exception.  I just wanted to note this for the public.

These four Squarespace web servers have been getting blocked for a few weeks:

ext-sq.squarespace.com. 151     IN      A       198.185.159.145
ext-sq.squarespace.com. 151     IN      A       198.49.23.144
ext-sq.squarespace.com. 151     IN      A       198.185.159.144
ext-sq.squarespace.com. 151     IN      A       198.49.23.145

AFAIK that's any web server Squarespace hosts.  Occasionally they must drop out since they sometimes do work, like yesterday afternoon.

**Comment by jpgpi250** [comment]
198.185.159.145 hewittnet.us, part of cidr 198.185.159.0/24
198.49.23.144 hewittnet.us, part of cidr 198.49.23.0/24
198.185.159.144 hewittnet.us, part of cidr 198.185.159.0/24
198.49.23.145 hewittnet.us, part of cidr 198.49.23.0/24

hewittnet.us -> list 15: https://raw.githubusercontent.com/jbaggs/doh-intel/master/doh.intel

if you need an exception, read the section "CIDR (network) Exceptions" in the [manual](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf).

It is recommended to use rpz, when adding exceptions, see [manual](https://jpgpi250.github.io/piholemanual/doc/Unbound%20response%20policy%20zones.pdf),
zone file https://raw.githubusercontent.com/jpgpi250/piholemanual/master/DOH.rpz

**Comment by jpgpi250** [comment]
closed after 21 days without response
