### ISSUE TITLE
IP's not in the list

### ISSUE THREAD

**Issue by Hemingray42** [jpgpi250/piholemanual#4]
Loaded this into pfSense today, and tested using Intra. Found these IPs not in the list that are operating as DoH resolvers: 

104.16.208.90
104.17.156.85
104.17.175.85
104.17.176.85
149.112.122.10
149.112.121.10
94.130.106.88
93.177.65.183

**Comment by jpgpi250** [comment]
Found the list of DoH resolvers in the code ([github](https://github.com/Jigsaw-Code/Intra)) off the intra app [here](https://raw.githubusercontent.com/Jigsaw-Code/Intra/master/Android/app/src/main/res/values/servers.xml).

This new list will now also be processed (daily) by the script, new entries will be added to the resulting IP lists.

The [documentation](http://users.telenet.be/MySQLplaylist/blockDOH.pdf) has been updated.

**Comment by jpgpi250** [comment]
closed after 21 days
