### ISSUE TITLE
Cloudflare IP has been add to IPv4 BlockList

### ISSUE THREAD

**Issue by mbah-dukun** [jpgpi250/piholemanual#40]
hello, how to remove iplist from list?
because is block my blog in cloudflare

172.67.216.46
104.21.45.153
2606:4700:3032::6815:2d99
2606:4700:3034::ac43:d82e

**Comment by jpgpi250** [comment]
172.67.216.46 -> adguard.lista.my.id, dns.lista.my.id, onic-doh.lista.my.id
104.21.45.153 -> adguard.lista.my.id, dns.lista.my.id, onic-doh.lista.my.id
2606:4700:3032::6815:2d99 -> adguard.lista.my.id, dns.lista.my.id, onic-doh.lista.my.id
2606:4700:3034::ac43:d82e -> adguard.lista.my.id, dns.lista.my.id, onic-doh.lista.my.id

adguard.lista.my.id -> list 7, 15
dns.lista.my.id -> list 7, 15
onic-doh.lista.my.id -> list 7, 15

list7: https://raw.githubusercontent.com/wiki/curl/curl/DNS-over-HTTPS.md
list15: https://raw.githubusercontent.com/jbaggs/doh-intel/master/doh.intel

- create an exception, see the [manual](https://jpgpi250.github.io/piholemanual/doc/Block%20DOH%20with%20pfsense.pdf)
- don't use this list(s)

**Comment by mbah-dukun** [comment]
Yes, but in same ip has stats.lista.my.id , dash.lista.my.id , idnet.eu.org cloud.lista.my.id etc

https://search.dnslytics.com/search?q=ip:+%22172.67.216.46%22&d=domains

**Comment by jpgpi250** [comment]
There are lots of services that share the same IP as the DOH service in the lists. Administrators, who are using the IP lists on the firewall, need to be knowledgeable enough to implement exceptions for services, they want to allow. If the required knowledge to implement exceptions is not available, don't use the lists.
