### ISSUE TITLE
Cleanbrowsing DOH is not being blocked

### ISSUE THREAD

**Issue by fotingo** [jpgpi250/piholemanual#44]
When selecting https://doh.cleanbrowsing.org/doh/family-filter{?dns} as the Secure DNS server on any browser, it bypasses any filtering.

**Comment by jpgpi250** [comment]
doh.cleanbrowsing.org is in a lot of lists (screenshot)

![image](https://github.com/jpgpi250/piholemanual/assets/24669386/59a4f15b-fdc1-494e-bd7c-47db607ab4ac)

doh.cleanbrowsing.org resolves to:
```
dig @127.10.10.5 -p 5555 +short doh.cleanbrowsing.org
185.228.168.168
185.228.168.10
```
these ip's are in the [ipv4 list](https://github.com/jpgpi250/piholemanual/blob/master/DOHipv4.txt)

maybe:
- the ip's are in your exception list
- the ip's are different for your region, see [issue 7](https://github.com/jpgpi250/piholemanual/issues/7)

can't fix ...

**Comment by fotingo** [comment]
I got it to work. It was an issue with my Pihole.
Thanks.
