### ISSUE TITLE
remove request

### ISSUE THREAD

**Issue by Suspectxyzz** [jpgpi250/piholemanual#45]
hello, I saw that my domain is blacklisted in your list , you can check it yourself.
meowless.club CNAME .

**Comment by jpgpi250** [comment]
I don't add / remove domain entries, I only consolidate (o)DoH lists

meowless.club is on list 15 (https://raw.githubusercontent.com/jbaggs/doh-intel/master/doh.intel), you'll need to contact the owner of this list if you want it removed.
