### ISSUE TITLE
Another DoH source to add

### ISSUE THREAD

**Issue by hugepants** [jpgpi250/piholemanual#8]
Hi. Excellent work on the most comprehensive list around.

The following source has several IPs that are not present in your consolidated list.
https://github.com/dibdot/DoH-IP-blocklists

Thanks for your consideration.

**Comment by jpgpi250** [comment]
Thank you for reporting this.

I will add these DoH servers to the list. The IP's will only be added if:
- it's a valid IP.
- the DNS domain exists.

This test is executed for all entries, added to the consolidated list, It will take a while to write the script to test this (yet another list format)...

I will let you know when it's completed.

**Comment by hugepants** [comment]
Understood, thank you for your efforts.

**Comment by jpgpi250** [comment]
Both lists have been added, [documentation](http://users.telenet.be/MySQLplaylist/blockDOH.pdf) has been updated to reflect the changes.
